services:
   mongo:
      image: mongo:6.0
      container_name: fotff-mongo
      restart: always
      ports:
         - '27017:27017'
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOTUSER}
         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOTPASSWORD}
         MONGO_INITDB_DATABASE: fortress_of_the_fallen
      volumes:
         - ./data/mongo:/data/db
         - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
      networks:
         - fotff
      extra_hosts:
         - 'host.docker.internal:host-gateway'

   redis:
      image: redis/redis-stack:latest
      container_name: fotff-redis
      ports:
         - '6379:6379'
         - '8011:8001'
      networks:
         - fotff
      extra_hosts:
         - 'host.docker.internal:host-gateway'

   minio:
      image: minio/minio:RELEASE.2023-03-20T20-16-18Z
      container_name: fotff-minio
      ports:
         - '9000:9000'
         - '9001:9001'
      volumes:
         - ./data/minio_data:/data
      environment:
         MINIO_ROOT_USER: ${MINIO_ROOTUSER}
         MINIO_ROOT_PASSWORD: ${MINIO_ROOTPASSWORD}
      command: server /data --console-address ":9001"

   mc-init:
      image: minio/mc
      container_name: fotff-mc
      depends_on:
         - minio
      entrypoint: >
         /bin/sh -c "
           sleep 5;
           mc alias set myminio http://minio:9000 ${MINIO_ROOTUSER} ${MINIO_ROOTPASSWORD} &&
           mc mb myminio/${MINIO_BUCKET_NAME} || true &&
           mc admin user add myminio ${MINIO_USER} ${MINIO_USERPASSWORD} &&
           mc admin policy attach myminio readwrite --user ${MINIO_USER}
           echo '✅ MinIO user created';
         "

networks:
   fotff:
