export enum ApiErrorCode {
   Unauthorized = 'UNAUTHORIZED',
   Forbidden = 'FORBIDDEN',
   ValidationFailed = 'VALIDATION_FAILED',
   ConfigVersionMissing = 'CONFIG_VERSION_MISSING',
   NotFound = 'NOT_FOUND',
   UsernameTaken = 'USERNAME_TAKEN',
   InvalidCredentials = 'INVALID_CREDENTIALS',
   InsufficientGold = 'INSUFFICIENT_GOLD',
   InsufficientResource = 'INSUFFICIENT_RESOURCE',
   InsufficientResources = 'INSUFFICIENT_RESOURCES',
   AlreadyClaimed = 'ALREADY_CLAIMED',
   HeroInstanceNotFound = 'HERO_INSTANCE_NOT_FOUND',
   MaxCastleLevel = 'MAX_CASTLE_LEVEL',
   ConfigVersionMismatch = 'CONFIG_VERSION_MISMATCH',
   ConfigMismatch = 'CONFIG_VERSION_MISMATCH',
   BattleExpired = 'BATTLE_EXPIRED',
   BattleAlreadyFinished = 'BATTLE_ALREADY_FINISHED',
   IdempotencyConflict = 'IDEMPOTENCY_CONFLICT',
   InternalServerError = 'INTERNAL_SERVER_ERROR',
}
